services:
  cabe-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cabe_flask_app
    restart: unless-stopped
    ports:
      - "8100:80"  # Format: "HOST:CONTAINER" (Akses via http://localhost:8100 atau IP_VPS:8100)
    volumes:
      - ./static:/app/static
      - ./model:/app/model
      - ./templates:/app/templates
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=80
